In [2]:
import os;
import sys;
import pickle;
import numpy as np;

In [28]:
def L_i(x, y, W):
    """
    unvectorized version. Compute the multiclass svm loss for a single example (x,y)
    - x is a column vector representing an image (e.g. 3073 x 1 in CIFAR-10)
    with an appended bias dimension in the 3073-rd position (i.e. bias trick)
    - y is an integer giving index of correct class (e.g. between 0 and 9 in CIFAR-10)
    - W is the weight matrix (e.g. 10 x 3073 in CIFAR-10)
    """
    delta = 1.0 # see notes about delta later in this section
    scores = W.dot(x) # scores becomes of size 10 x 1, the scores for each class
    correct_class_score = scores[y]
    D = W.shape[0] # number of classes, e.g. 10
    loss_i = 0.0
    for j in xrange(D): # iterate over all wrong classes
        if j == y:
            # skip for the true class to only loop over incorrect classes
            continue
        # accumulate loss for the i-th example
        loss_i += max(0, scores[j] - correct_class_score + delta)
    return loss_i

def L_i_vectorized(x, y, W):
    """
    A faster half-vectorized implementation. half-vectorized
    refers to the fact that for a single example the implementation contains
    no for loops, but there is still one loop over the examples (outside this function)
    """
    delta = 1.0
    scores = W.dot(x)
    # compute the margins for all classes in one vector operation
    margins = np.maximum(0, scores - scores[y] + delta)
    # on y-th position scores[y] - scores[y] canceled and gave delta. We want
    # to ignore the y-th position and only consider margin on max wrong class
    margins[y] = 0
    loss_i = np.sum(margins)
    return loss_i

def L(X, y, W):
    """ 
    fully-vectorized implementation :
    - X holds all the training examples as columns (e.g. 3073 x 50,000 in CIFAR-10)
    - y is array of integers specifying correct class (e.g. 50,000-D array)
    - W are weights (e.g. 10 x 3073)
    """
    # evaluate loss over all examples in X without using any for loops
    # left as exercise to reader in the assignment
    delta = 1.0
    scores = W.dot(X)
    num = scores.shape[1]
    # remember interger indexing in python, very important(different from MATLAB)
    margins = np.maximum(0, scores - scores[y,np.arange(num)] + delta); 
    margins[y,np.arange(num)] = 0
    loss_i = np.sum(margins)
    return loss_i
def regulizaion(W):
    londa = 1.0
    rW=np.sum(np.square(W,W))
    return rW

In [29]:
X=np.random.rand(3,5)
y=np.random.randint(10, size=5)
W=np.random.rand(10,3)
print(X,"\n",y,"\n",W)
L(X, y, W)
regulizaion(W)

[[ 0.70816431  0.03442109  0.17010297  0.90296702  0.29542718]
 [ 0.25466689  0.68703178  0.26016867  0.66361788  0.50326851]
 [ 0.10300962  0.16751117  0.50849381  0.27337434  0.02334002]] 
 [7 7 2 9 2] 
 [[ 0.11872983  0.19310517  0.58068263]
 [ 0.01050618  0.75176593  0.91528878]
 [ 0.21047062  0.03868682  0.62935613]
 [ 0.74527119  0.53997264  0.57182823]
 [ 0.91526212  0.79915543  0.17714735]
 [ 0.66452543  0.96679452  0.94113623]
 [ 0.49490059  0.6457706   0.92826558]
 [ 0.89506545  0.7930193   0.58328426]
 [ 0.48554148  0.22690476  0.28560906]
 [ 0.86400159  0.67749893  0.85137499]]
[[  1.40967714e-02   3.72896084e-02   3.37192317e-01]
 [  1.10379795e-04   5.65152015e-01   8.37753559e-01]
 [  4.42978812e-02   1.49666996e-03   3.96089136e-01]
 [  5.55429146e-01   2.91570447e-01   3.26987520e-01]
 [  8.37704750e-01   6.38649405e-01   3.13811843e-02]
 [  4.41594042e-01   9.34691644e-01   8.85737403e-01]
 [  2.44926593e-01   4.17019666e-01   8.61676978e-01]
 [  8.01142164e-01   6.28

12.770241175319351